name: falco

on:
  push:
    paths:
      - '.github/workflows/falco.yml'
      - 'build/falco/**'
      - '!build/falco/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/falco/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=FALCO_VERSION=${{ env.VERSION }} \
            --tag raspbernetes/falco:${{ github.sha }} \
            -f ./build/falco/Dockerfile \
            ./build/falco/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=FALCO_VERSION=${{ env.VERSION }} \
            --tag raspbernetes/falco:latest \
            --tag raspbernetes/falco:${{ env.VERSION }} \
            -f ./build/falco/Dockerfile \
            ./build/fluxd/ \
            --push
